import { EnvVarReference } from "../domain/env-var";

const HEADER_LINES = [
  "# Generated by the Copilot to OpenCode migration toolkit.",
  "# Placeholder values only; fill them in locally and never commit real secrets.",
  "",
];

export function mergeEnvVars(
  groups: readonly (readonly EnvVarReference[])[],
): EnvVarReference[] {
  const byName = new Map<string, EnvVarReference>();

  for (const group of groups) {
    for (const reference of group) {
      const existing = byName.get(reference.name);
      if (existing === undefined) {
        byName.set(reference.name, reference);
      } else if (!existing.consumer.split(", ").includes(reference.consumer)) {
        byName.set(reference.name, {
          name: reference.name,
          consumer: `${existing.consumer}, ${reference.consumer}`,
        });
      }
    }
  }

  return [...byName.values()].sort((left, right) => left.name.localeCompare(right.name));
}

export function renderEnvExample(references: readonly EnvVarReference[]): string {
  const lines = [...HEADER_LINES];
  for (const reference of references) {
    lines.push(`# consumer: ${reference.consumer}`, `${reference.name}=`);
  }
  lines.push("");
  return lines.join("\n");
}
